pipeline {
    agent any

    environment{
        name="navid"
    }
    stages {
        stage('Build') {
            steps {
                sh 'dotnet build'
                sh 'echo ${name}'
            }
        }
    }

    post {

        success {
            echo 'Build Succeeded'
        }

        failure {
            echo 'Build Failed'
        }

        always {
            echo 'Cleanup'
        }
    }
}
